name: zedtool-env
channels:
  - conda-forge
dependencies:
  - aiohttp=3.12.15
  - fsspec=2025.7
  - matplotlib=3.9.4
  - myst-parser
  - numpy=1.26.4
  - pandas=2.3.2
  - pillow=11.3
  - plotly=6.3
  - psutil=7.1.0
  - pyarrow=21.0.0
  - python=3.12
  - pyyaml=6.0
  - requests=2.32.5
  - scipy=1.12
  - scikit-learn=1.7.1
  - scikit-image=0.24.0
  - sphinx_rtd_theme
  - tifffile=2025.9.9

