name: zedtool-env
channels:
  - conda-forge
dependencies:
  - aiohttp=3.12.15
  - fsspec=2025.7
  - matplotlib=3.7
  - myst-parser
  - numpy=1.25
  - pandas=2.3.2
  - pillow=11.3
  - plotly=6.3
  - pyarrow
  - python=3.11.13
  - pyyaml=6.0
  - requests=2.32.5
  - scipy=1.10
  - scikit-learn=1.7.1
  - scikit-image=0.24.0
  - sphinx_rtd_theme
  - tifffile=2025.9.9

