name: zedtool-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=11.1.0
  - plotly=5.22.0
  - pyyaml=6.0.2
  - scikit-learn=1.2.0
  - scipy=1.10.0
  - scikit-image=0.19.3
  - tifffile=2021.7.2
  - fsspec=2025.3.2
  - requests=2.32.3
  - pyarrow=19.0.1
  - aiohttp

