name: zedtool-env-312
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.12.15
  - fsspec=2025.7.0
  - matplotlib=3.10.6
  - myst-parser
  - numpy=2.3.2
  - pandas=2.3.2
  - pillow=11.3.0
  - plotly=6.3.0
  - pyarrow=21.0.0
  - pyyaml=6.0.2
  - python=3.12
  - requests=2.32.5
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - scikit-image=0.25.2
  - sphinx_rtd_theme
  - tifffile=2025.8.28

